Add -t option to continuously

diff --git a/bin/continuously b/bin/continuously
--- a/bin/continuously
+++ b/bin/continuously
@@ -1,5 +1,14 @@
 #!/bin/bash
 
+TARGET=.
+while getopts "t:" OPT; do
+    case $OPT in
+        t) TARGET=$OPTARG ;;
+        \?) echo "Invalid option: -$OPTARG" >&2; exit 2 ;;
+    esac
+done
+shift $((OPTIND-1))
+
 manual_waiter() {
   read -sp "[wait] " < /dev/tty && echo 1>&2 "[manual trigger]"
 }
@@ -10,13 +19,10 @@ file_waiter() {
   echo 1>&2 "[file trigger]"
 }
 
-TARGET=$1
-shift
-
 while true; do
-  (manual_waiter) &
+  manual_waiter &
   manual_pid=$!
-  (file_waiter "$TARGET") &
+  file_waiter "$TARGET" &
   file_pid=$!
 
   trap "kill $manual_pid $file_pid; echo; exit 0" INT
