Add batch of changes from the x280

diff --git a/bin/continuously b/bin/continuously
--- a/bin/continuously
+++ b/bin/continuously
@@ -5,20 +5,28 @@ set -o nounset -o pipefail -o errexit
 TMP=$(mktemp -d)
 trap 'rm -rf $TMP' EXIT
 
-WRAPPER=$(pwd)/.k
-while getopts "t:w:-" OPT; do
+ACTION=run
+while getopts "t:c-" OPT; do
     case $OPT in
-        t) echo -ne "$OPTARG\0" >> "$TMP/targets" ;;
-        w) WRAPPER=$OPTARG ;;
-        -) break ;;
-        \?) echo "Invalid option: -$OPTARG" >&2; exit 2 ;;
+        t) echo -ne "$OPTARG\0" >> "$TMP/targets";;
+        c) ACTION=completion-script; COMPLETE_NAME=$(basename "$0");;
+        -) break;;
+        \?) echo "Invalid option: -$OPTARG" >&2; exit 2;;
     esac
 done
 shift $((OPTIND-1))
 
+if [ "$ACTION" = "completion-script" ]; then
+    cat <<EOF
+_continuously_completion() {
+}
+complete -F _continuously_completion "$COMPLETE_NAME"
+EOF
+fi
+
 manual_waiter() {
-    read -sp "[wait] " < /dev/tty
-    kill $(<"$TMP/file.pid")
+    read -rsp "[wait] " < /dev/tty
+    kill "$(<"$TMP/file.pid")"
     echo 1>&2 "[manual trigger]"
 }
 
@@ -28,7 +36,7 @@ files() {
 
 file_waiter() {
     files | tr '\0' '\n' | inotifywait --fromfile=- -e close_write,moved_to,move_self --format="%f" --quiet
-    kill $(<"$TMP/manual.pid")
+    kill "$(<"$TMP/manual.pid")"
     echo 1>&2 "[file trigger]"
 }
 
@@ -46,7 +54,8 @@ while true; do
 
     wait
 
-    ( if [ -f "$WRAPPER" ]; then /bin/sh "$WRAPPER" $*; else $*; fi ) &
+    sleep 0.1
+    ( "$@" ) &
     echo "$!" > "$TMP/child.pid"
     set +o errexit
     wait
