Add batch of config changes from the x280

diff --git a/bin/httpflow b/bin/httpflow
--- a/bin/httpflow
+++ b/bin/httpflow
@@ -6,7 +6,7 @@ while getopts "i:p:" opt; do
     case $opt in
         i) I=$OPTARG ;;
         p) FILTERS="$FILTERS or port $OPTARG" ;;
-        \?) echo "Invalid option: -$OPTARG" 1>&2 exit 2 ;;
+        \?) echo "Invalid option: -$OPTARG" 1>&2; exit 2 ;;
     esac
 done
 shift $((OPTIND-1))
